#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"
. "$ROOT/scripts/_trap"

. "$HERE/../_env"

kubectl delete --ignore-not-found=true --filename="https://raw.githubusercontent.com/intel/multus-cni/$MULTUS_VERSION/images/multus-daemonset.yml"
