#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"
. "$ROOT/scripts/_trap"

# https://intel.github.io/multus-cni/doc/quickstart.html

if [ "$1" == -c ]; then
	"$HERE/delete"
fi

. "$HERE/../_env"

m 'deploying Multus...'
kubectl apply --filename="https://raw.githubusercontent.com/intel/multus-cni/$MULTUS_VERSION/images/multus-daemonset.yml"

m 'waiting for Multus to start...'
POD=$(kubectl get pods --namespace=kube-system --selector=app=multus --output=jsonpath={.items[0].metadata.name})
kubectl wait "pods/$POD" --namespace=kube-system \
	--for=condition=ContainersReady

m 'restarting CRI-O...'
minikube ssh -- sudo systemctl restart crio
