// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	scheme "github.com/tliron/turandot/apis/clientset/versioned/scheme"
	v1alpha1 "github.com/tliron/turandot/resources/turandot.puccini.cloud/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// InventoriesGetter has a method to return a InventoryInterface.
// A group's client should implement this interface.
type InventoriesGetter interface {
	Inventories(namespace string) InventoryInterface
}

// InventoryInterface has methods to work with Inventory resources.
type InventoryInterface interface {
	Create(ctx context.Context, inventory *v1alpha1.Inventory, opts v1.CreateOptions) (*v1alpha1.Inventory, error)
	Update(ctx context.Context, inventory *v1alpha1.Inventory, opts v1.UpdateOptions) (*v1alpha1.Inventory, error)
	UpdateStatus(ctx context.Context, inventory *v1alpha1.Inventory, opts v1.UpdateOptions) (*v1alpha1.Inventory, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Inventory, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.InventoryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Inventory, err error)
	InventoryExpansion
}

// inventories implements InventoryInterface
type inventories struct {
	client rest.Interface
	ns     string
}

// newInventories returns a Inventories
func newInventories(c *TurandotV1alpha1Client, namespace string) *inventories {
	return &inventories{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the inventory, and returns the corresponding inventory object, and an error if there is any.
func (c *inventories) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Inventory, err error) {
	result = &v1alpha1.Inventory{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("inventories").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Inventories that match those selectors.
func (c *inventories) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InventoryList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.InventoryList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("inventories").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested inventories.
func (c *inventories) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("inventories").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a inventory and creates it.  Returns the server's representation of the inventory, and an error, if there is any.
func (c *inventories) Create(ctx context.Context, inventory *v1alpha1.Inventory, opts v1.CreateOptions) (result *v1alpha1.Inventory, err error) {
	result = &v1alpha1.Inventory{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("inventories").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inventory).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a inventory and updates it. Returns the server's representation of the inventory, and an error, if there is any.
func (c *inventories) Update(ctx context.Context, inventory *v1alpha1.Inventory, opts v1.UpdateOptions) (result *v1alpha1.Inventory, err error) {
	result = &v1alpha1.Inventory{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("inventories").
		Name(inventory.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inventory).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *inventories) UpdateStatus(ctx context.Context, inventory *v1alpha1.Inventory, opts v1.UpdateOptions) (result *v1alpha1.Inventory, err error) {
	result = &v1alpha1.Inventory{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("inventories").
		Name(inventory.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inventory).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the inventory and deletes it. Returns an error if one occurs.
func (c *inventories) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("inventories").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *inventories) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("inventories").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched inventory.
func (c *inventories) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Inventory, err error) {
	result = &v1alpha1.Inventory{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("inventories").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
