#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/scripts/_env"
. "$ROOT/scripts/_trap"

cd "$HERE/../telephony-network-service"

# central

minikube profile central

multus/deploy
kubevirt/deploy

# edge

minikube profile edge

multus/deploy
