#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"
. "$ROOT/scripts/_trap"

. "$HERE/../_env"

kubectl delete -f "https://github.com/kubevirt/kubevirt/releases/download/v$KUBEVIRT_VERSION/kubevirt-cr.yaml" || true
kubectl delete configmaps kubevirt-config -n kubevirt || true

# https://kubevirt.io/user-guide/docs/latest/administration/intro.html#delete
kubectl delete apiservices v1alpha3.subresources.kubevirt.io || true # blocking leftover
kubectl delete mutatingwebhookconfigurations virt-api-mutator || true # non-blocking leftover
kubectl delete validatingwebhookconfigurations virt-api-validator || true # non-blocking leftover

kubectl delete -f "https://github.com/kubevirt/kubevirt/releases/download/v$KUBEVIRT_VERSION/kubevirt-operator.yaml" || true

#kubectl delete kubevirts kubevirt --namespace kubevirt || true
#kubectl delete deployments virt-operator --namespace kubevirt || true
#kubectl delete clusterroles kubevirt-operator || true
#kubectl delete serviceaccounts kubevirt-operator --namespace kubevirt || true
#kubectl delete clusterroles kubevirt.io:operator || true
#kubectl delete crds kubevirts.kubevirt.io || true
#"$HERE/nuke-namespace" kubevirt || true
#kubectl delete namespaces kubevirt || true
