// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tliron/turandot/resources/turandot.puccini.cloud/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInventories implements InventoryInterface
type FakeInventories struct {
	Fake *FakeTurandotV1alpha1
	ns   string
}

var inventoriesResource = schema.GroupVersionResource{Group: "turandot.puccini.cloud", Version: "v1alpha1", Resource: "inventories"}

var inventoriesKind = schema.GroupVersionKind{Group: "turandot.puccini.cloud", Version: "v1alpha1", Kind: "Inventory"}

// Get takes name of the inventory, and returns the corresponding inventory object, and an error if there is any.
func (c *FakeInventories) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Inventory, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(inventoriesResource, c.ns, name), &v1alpha1.Inventory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Inventory), err
}

// List takes label and field selectors, and returns the list of Inventories that match those selectors.
func (c *FakeInventories) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InventoryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(inventoriesResource, inventoriesKind, c.ns, opts), &v1alpha1.InventoryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.InventoryList{ListMeta: obj.(*v1alpha1.InventoryList).ListMeta}
	for _, item := range obj.(*v1alpha1.InventoryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inventories.
func (c *FakeInventories) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(inventoriesResource, c.ns, opts))

}

// Create takes the representation of a inventory and creates it.  Returns the server's representation of the inventory, and an error, if there is any.
func (c *FakeInventories) Create(ctx context.Context, inventory *v1alpha1.Inventory, opts v1.CreateOptions) (result *v1alpha1.Inventory, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(inventoriesResource, c.ns, inventory), &v1alpha1.Inventory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Inventory), err
}

// Update takes the representation of a inventory and updates it. Returns the server's representation of the inventory, and an error, if there is any.
func (c *FakeInventories) Update(ctx context.Context, inventory *v1alpha1.Inventory, opts v1.UpdateOptions) (result *v1alpha1.Inventory, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(inventoriesResource, c.ns, inventory), &v1alpha1.Inventory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Inventory), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInventories) UpdateStatus(ctx context.Context, inventory *v1alpha1.Inventory, opts v1.UpdateOptions) (*v1alpha1.Inventory, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(inventoriesResource, "status", c.ns, inventory), &v1alpha1.Inventory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Inventory), err
}

// Delete takes name of the inventory and deletes it. Returns an error if one occurs.
func (c *FakeInventories) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(inventoriesResource, c.ns, name), &v1alpha1.Inventory{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInventories) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(inventoriesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.InventoryList{})
	return err
}

// Patch applies the patch and returns the patched inventory.
func (c *FakeInventories) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Inventory, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(inventoriesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Inventory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Inventory), err
}
