// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	turandotpuccinicloudv1alpha1 "github.com/tliron/turandot/apis/applyconfiguration/turandot.puccini.cloud/v1alpha1"
	v1alpha1 "github.com/tliron/turandot/resources/turandot.puccini.cloud/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=turandot.puccini.cloud, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Service"):
		return &turandotpuccinicloudv1alpha1.ServiceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceNodeModeState"):
		return &turandotpuccinicloudv1alpha1.ServiceNodeModeStateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceSpec"):
		return &turandotpuccinicloudv1alpha1.ServiceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceStatus"):
		return &turandotpuccinicloudv1alpha1.ServiceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceTemplate"):
		return &turandotpuccinicloudv1alpha1.ServiceTemplateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceTemplateDirect"):
		return &turandotpuccinicloudv1alpha1.ServiceTemplateDirectApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceTemplateIndirect"):
		return &turandotpuccinicloudv1alpha1.ServiceTemplateIndirectApplyConfiguration{}

	}
	return nil
}
