#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"
. "$ROOT/scripts/_trap"

# https://cert-manager.io/docs/installation/kubernetes/

if [ "$1" == -c ]; then
	"$HERE/delete"
fi

. "$HERE/../_env"

m 'deploying cert-manager...'
kubectl apply --filename="https://github.com/jetstack/cert-manager/releases/download/v$CERT_MANAGER_VERSION/cert-manager.yaml"

m 'waiting for cert-manager to start...'
POD=$(kubectl get pods --namespace=cert-manager --selector=app=webhook --output=jsonpath={.items[0].metadata.name})
kubectl wait "pods/$POD" --namespace=cert-manager \
	--for=condition=ContainersReady
