tosca_definitions_version: tosca_simple_yaml_1_3

imports:

- capabilities.yaml
- relationships.yaml

node_types:

  Service:
    description: >-
      Represents a microservice: a controlled pod (Deployment) plus a controlled endpoint (Service).
    capabilities:
      metadata: Metadata
      service: Service
      deployment: Deployment
    requirements:
    - route:
        capability: Service
        relationship: Route
        occurrences: [ 0, UNBOUNDED ]
