#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../../scripts/_env"
. "$ROOT/scripts/_trap"

IMAGES=$(readlink --canonicalize "$HERE/../artifacts/images")

mkdir --parents "$IMAGES"

"$ROOT/scripts/save-portable-container-image" localhost/asterisk-cnf "$IMAGES/asterisk-cnf.tar.gz"
"$ROOT/scripts/save-portable-container-image" localhost/asterisk-vnf "$IMAGES/asterisk-vnf.tar.gz"
