#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../scripts/_env"

"$HERE/hello-world/scripts/build-csar"
"$HERE/self-contained/scripts/build-csar"
"$HERE/helm/scripts/build-csar"
"$HERE/telephony-network-service/scripts/build-csars"
