// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ServiceTemplateIndirectApplyConfiguration represents an declarative configuration of the ServiceTemplateIndirect type for use
// with apply.
type ServiceTemplateIndirectApplyConfiguration struct {
	Namespace *string `json:"namespace,omitempty"`
	Registry  *string `json:"registry,omitempty"`
	Name      *string `json:"name,omitempty"`
}

// ServiceTemplateIndirectApplyConfiguration constructs an declarative configuration of the ServiceTemplateIndirect type for use with
// apply.
func ServiceTemplateIndirect() *ServiceTemplateIndirectApplyConfiguration {
	return &ServiceTemplateIndirectApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ServiceTemplateIndirectApplyConfiguration) WithNamespace(value string) *ServiceTemplateIndirectApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithRegistry sets the Registry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Registry field is set to the value of the last call.
func (b *ServiceTemplateIndirectApplyConfiguration) WithRegistry(value string) *ServiceTemplateIndirectApplyConfiguration {
	b.Registry = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ServiceTemplateIndirectApplyConfiguration) WithName(value string) *ServiceTemplateIndirectApplyConfiguration {
	b.Name = &value
	return b
}
