// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ServiceTemplateApplyConfiguration represents an declarative configuration of the ServiceTemplate type for use
// with apply.
type ServiceTemplateApplyConfiguration struct {
	Direct   *ServiceTemplateDirectApplyConfiguration   `json:"direct,omitempty"`
	Indirect *ServiceTemplateIndirectApplyConfiguration `json:"indirect,omitempty"`
}

// ServiceTemplateApplyConfiguration constructs an declarative configuration of the ServiceTemplate type for use with
// apply.
func ServiceTemplate() *ServiceTemplateApplyConfiguration {
	return &ServiceTemplateApplyConfiguration{}
}

// WithDirect sets the Direct field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Direct field is set to the value of the last call.
func (b *ServiceTemplateApplyConfiguration) WithDirect(value *ServiceTemplateDirectApplyConfiguration) *ServiceTemplateApplyConfiguration {
	b.Direct = value
	return b
}

// WithIndirect sets the Indirect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Indirect field is set to the value of the last call.
func (b *ServiceTemplateApplyConfiguration) WithIndirect(value *ServiceTemplateIndirectApplyConfiguration) *ServiceTemplateApplyConfiguration {
	b.Indirect = value
	return b
}
