#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

for ARG in "$@"; do
	case "$ARG" in
		-c)
			NAMESPACE=$WORKSPACE "$HERE/delete"
			;;
		--cluster)
			CLUSTER_MODE=true
			;;
	esac
done

export VERSION=1.0
export REGISTRY_URL=$(kubectl_registry_url)

kubectl create namespace "$WORKSPACE" || true

m "deploying operator to namespace \"$WORKSPACE\"..."
kubectl_apply_template "$ROOT/assets/kubernetes/custom-resource-definition.yaml"
kubectl_apply_template "$ROOT/assets/namespace.yaml"
if [ "$CLUSTER_MODE" == true ]; then
	kubectl_apply_template "$ROOT/assets/kubernetes/cluster-mode-authorization.yaml"
fi
kubectl_apply_template "$ROOT/assets/kubernetes/turandot.yaml"
kubectl_apply_template "$ROOT/assets/kubernetes/hello-world.yaml"

m "waiting for operator to start..."
kubectl_wait_for_deployment turandot-operator
