#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

go install "$ROOT/turandot-profile-generator"

turandot-profile-generator "$ROOT/assets/profile-generator/kubernetes.yaml"
turandot-profile-generator "$ROOT/assets/profile-generator/kubevirt.yaml"
