#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

m 'Login to docker.io'
buildah login docker.io

function push () {
	local EXECUTABLE=$1
	local IMAGE=$EXECUTABLE
	local LOCAL=localhost/$IMAGE
	local REMOTE=docker://docker.io/tliron/$IMAGE
	#local REMOTE=docker://$(minikube ip):5000/tliron/$IMAGE

	skopeo delete --tls-verify=false "$REMOTE" || true
	buildah push --tls-verify=false "$LOCAL" "$REMOTE"
}

push turandot-operator
