#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

rm --force "$ROOT/go.mod" "$ROOT/go.sum"

cd "$ROOT"
go mod init "$MODULE"
go get k8s.io/client-go@v0.17.1

"$HERE/test"

go mod tidy
