#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../scripts/_env"
. "$ROOT/scripts/_trap"

minikube profile edge
turandot uninstall -n workspace -w -v
kubectl delete events --all --namespace=workspace

minikube profile central
turandot uninstall -n workspace -w -v
kubectl delete events --all --namespace=workspace

if [ "$1" == -b ]; then
	"$ROOT/scripts/build-container-image"
	"$ROOT/scripts/publish-container-image"
fi

kubectl config set-context central --namespace=workspace
kubectl config set-context edge --namespace=workspace

turandot install -s central -n workspace -w -v

turandot service deploy hello-world -f dist/hello-world.csar -v
turandot service deploy helm-hello-world -f dist/helm-hello-world.csar -v

turandot delegate set edge --delegate-context=edge -v

turandot template register telephony-network-service -f dist/telephony-network-service.csar -v
turandot template register simple-data-plane -f dist/simple-data-plane.csar -v
turandot template register asterisk-cnf -f dist/asterisk-cnf.csar -v
turandot template register asterisk-vnf -f dist/asterisk-vnf.csar -v

turandot service deploy telephony-network-service -t telephony-network-service -i namespace=workspace -v

turandot operator logs -f

# Clean ~/.local/share/containers/ occassionally!
