#!/bin/bash
set -e

if [ "$EUID" -ne 0 ]; then
	echo "Run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../scripts/_env"
. "$HERE/_env"

FORCE=false
if [ "$1" == -f ]; then
	FORCE=true
fi

install_tool minikube "$MINIKUBE_VERSION" \
"https://storage.googleapis.com/minikube/releases/v$MINIKUBE_VERSION/minikube-linux-amd64"

install_tool kubectl "$KUBECTL_VERSION" \
"https://storage.googleapis.com/kubernetes-release/release/v$KUBECTL_VERSION/bin/linux/amd64/kubectl"

"$HERE/kubevirt/install" "$1"

"$HERE/cert-manager/install" "$1"
