#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../scripts/_env"

function github_version () {
	local REPO=$1
	curl --silent "https://api.github.com/repos/$REPO/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'	
}

KUBERNETES_VERSION=$(curl --silent https://storage.googleapis.com/kubernetes-release/release/stable.txt)
MINIKUBE_VERSION=$(github_version kubernetes/minikube)
KUBEVIRT_VERSION=$(github_version kubevirt/kubevirt)
HELM_VERSION=$(github_version helm/helm)
YQ_VERSION=$(github_version mikefarah/yq)
MULTUS_VERSION=$(github_version intel/multus-cni)

m "KUBERNETES_VERSION=$KUBERNETES_VERSION"
m "MINIKUBE_VERSION=$MINIKUBE_VERSION"
m "KUBEVIRT_VERSION=$KUBEVIRT_VERSION"
m "HELM_VERSION=$HELM_VERSION"
m "YQ_VERSION=$YQ_VERSION"
m "MULTUS_VERSION=$MULTUS_VERSION"
