#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"
. "$ROOT/scripts/_trap"

#minikube profile edge
#turandot operator uninstall --namespace=workspace --wait -v
#turandot inventory uninstall --namespace=workspace --wait -v
#kubectl delete events --all --namespace=workspace

minikube profile central
turandot operator uninstall --namespace=workspace --wait -v
turandot inventory uninstall --namespace=workspace --wait -v
kubectl delete events --all --namespace=workspace

if [ "$1" == -b ]; then
	"$ROOT/scripts/build-container-image"
	"$ROOT/scripts/publish-container-image"
	# Reminder: clean ~/.local/share/containers/ occassionally!
fi

kubectl config set-context central --namespace=workspace
kubectl config set-context edge --namespace=workspace

turandot operator install --site=central --wait -v
turandot inventory install --wait -v
turandot inventory create default --provider=turandot --namespace=workspace --wait -v
#turandot inventory create default --provider=minikube --wait -v

turandot service deploy hello-world --file=dist/hello-world.csar -v
turandot operator logs --follow
exit

turandot service deploy helm-hello-world --file=dist/helm-hello-world.csar -v

turandot delegate set edge --delegate-context=edge -v

turandot template register telephony-network-service --file=dist/telephony-network-service.csar -v
turandot template register simple-data-plane --file=dist/simple-data-plane.csar -v
turandot template register asterisk-cnf --file=dist/asterisk-cnf.csar -v
turandot template register asterisk-vnf --file=dist/asterisk-vnf.csar -v

turandot service deploy telephony-network-service --template=telephony-network-service --input=namespace=workspace -v

turandot operator logs --follow
