#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"
. "$ROOT/scripts/_trap"

minikube profile central
kubectl config set-context --current --namespace=workspace

turandot operator uninstall --wait -v

kubectl delete events --all

if [ "$1" == -b ]; then
	"$ROOT/scripts/build-container-image"
	"$ROOT/scripts/publish-container-image"
	# Reminder: clean ~/.local/share/containers/ occassionally!
fi

turandot operator install --site=central --role=view --wait -v
reposure registry create default --provider=minikube --wait -v
reposure image delete default --all -v
turandot service deploy hello-world --file=dist/hello-world.csar -v
turandot service deploy helm-hello-world --file=dist/helm-hello-world.csar -v
turandot operator logs --follow
