#!/bin/bash
set -e

# Fedora requirements:
#   dnf install @virtualization
#   sudo usermod -a -G libvirt $(whoami)
#   newgrp libvirt

PROFILE=${1:-central}

case "$PROFILE" in
	central)
		IP_RANGE=10.96.0.0/12  # Binary: 00001010.01100000.00000000.00000000 (the default)
		MEMORY=8g
		DISK_SIZE=20g
		;;
	edge)
		IP_RANGE=10.112.0.0/12 # Binary: 00001010.01110000.00000000.00000000
		MEMORY=4g
		DISK_SIZE=10g
		;;
esac

if [ "$2" == -c ]; then
	minikube delete --profile="$PROFILE"
fi

# kvm2: hostNetwork=true (and tunnel) masquerades source ip address 

# Note: for CRI-O we cannot access the registry at localhost:5000
# See: https://github.com/kubernetes/minikube/issues/6982
# Note: With CNI + Docker cannot access the registry externally
# Note: setting --dns-domain will break external access to registry
# This error? "Unable to get host boot time: No such process"
# See: https://www.spinics.net/lists/virt-tools/msg13886.html

minikube start \
	--profile="$PROFILE" \
	--vm-driver=kvm2 \
	--container-runtime=cri-o \
	--cni=bridge \
	--addons=registry \
	--cpus=4 \
	--memory="$MEMORY" \
	--disk-size="$DISK_SIZE" \
	--service-cluster-ip-range="$IP_RANGE" \
	--feature-gates=SCTPSupport=true

# By default --service-cluster-ip-range will also set --insecure-registry
#	--insecure-registry="$IP_RANGE"
#	--insecure-registry=10.1.0.0/16
#	--kubernetes-version="$KUBERNETES_VERSION" \

minikube profile "$PROFILE"

# Workaround for: https://github.com/kubernetes/minikube/issues/11729
minikube ssh -- sudo systemctl restart crio

minikube dashboard \
	--profile="$PROFILE"

#minikube tunnel --cleanup=true
#minikube tunnel

#sudo ip route add 10.1.0.0/16 via $(minikube ip)
#kubectl port-forward service/registry --namespace=kube-system 5000:80
#podman run --privileged --publish=5000:5000 registry
