// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// InventoryListerExpansion allows custom methods to be added to
// InventoryLister.
type InventoryListerExpansion interface{}

// InventoryNamespaceListerExpansion allows custom methods to be added to
// InventoryNamespaceLister.
type InventoryNamespaceListerExpansion interface{}

// ServiceListerExpansion allows custom methods to be added to
// ServiceLister.
type ServiceListerExpansion interface{}

// ServiceNamespaceListerExpansion allows custom methods to be added to
// ServiceNamespaceLister.
type ServiceNamespaceListerExpansion interface{}
