// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// RepositoryListerExpansion allows custom methods to be added to
// RepositoryLister.
type RepositoryListerExpansion interface{}

// RepositoryNamespaceListerExpansion allows custom methods to be added to
// RepositoryNamespaceLister.
type RepositoryNamespaceListerExpansion interface{}

// ServiceListerExpansion allows custom methods to be added to
// ServiceLister.
type ServiceListerExpansion interface{}

// ServiceNamespaceListerExpansion allows custom methods to be added to
// ServiceNamespaceLister.
type ServiceNamespaceListerExpansion interface{}
