#!/bin/bash
set -e

if [ "$EUID" -ne 0 ]; then
	echo "Run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"
. "$HERE/../_env"

FORCE=false
if [ "$1" == -f ]; then
	FORCE=true
fi

install_tool minishift "$MINISHIFT_VERSION" \
"https://github.com/minishift/minishift/releases/download/v$MINISHIFT_VERSION/minishift-$MINISHIFT_VERSION-linux-amd64.tgz" \
"minishift-$MINISHIFT_VERSION-linux-amd64/"

# KVM driver for Minishift
# See: https://docs.okd.io/3.11/minishift/getting-started/setting-up-virtualization-environment.html#for-linux

EXEC=/usr/local/bin/docker-machine-driver-kvm
URL=https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-centos7

if [ "$FORCE" == true ] || [ ! -f "$EXEC" ]; then
	if wget --quiet --output-document="$EXEC" "$URL"; then
		chmod a+x "$EXEC"
		m "installed \"$EXEC\""
	else
		m "could not download from \"$URL\" to \"$EXEC\"" "$RED"
	fi
fi
