#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"
. "$HERE/_env"

minikube profile edge

EXTERNAL_IP=$(turandot service output asterisk-cnf udp-ip -n workspace)

cat "$HERE/linphonerc-edge.template" | \
IP=$EXTERNAL_IP NAT_IP=$LIBVIRT_GATEWAY envsubst > "$HERE/linphonerc-edge"

linphonec -c "$HERE/linphonerc-edge"
